"""Orchestrate fix-PR creation: branch → commit → PR.

Glues together branch.create_branch_for_drift, commit.commit_file_change,
pull_request.open_pull_request for a single drift → fix-PR transformation.

Routing:
  drift.source == "prd"  → kind = "code-fix"   (Claude는 보통 docs 제안서 생성)
  drift.source == "seed" → kind = "seed-fix"   (SEED.md 실제 수정)
"""
from __future__ import annotations

from typing import Any

from .branch import create_branch_for_drift
from .commit import FileChange, commit_file_change
from .drift import DriftItem
from .pull_request import open_pull_request


FIX_KIND_BY_SOURCE = {"prd": "code-fix", "seed": "seed-fix"}


def create_fix_pr(
    octokit: Any,
    *,
    owner: str,
    repo: str,
    drift: DriftItem,
    change: FileChange,
    rationale: str,
    base_sha: str,
    default_branch: str,
    source_pr_number: int,
    draft: bool = True,
) -> tuple[str, int]:
    """Create one fix-PR for one drift item.

    Returns ``(branch_name, new_pr_number)``.

    Always opens as draft by default — these PRs are bot-generated and
    should be reviewed before any merge.
    """
    kind = FIX_KIND_BY_SOURCE.get(drift.source, "fix")
    prefix = f"pr-guard/{kind}"
    branch, _ = create_branch_for_drift(
        octokit,
        owner=owner,
        repo=repo,
        drift=drift,
        base_sha=base_sha,
        prefix=prefix,
    )
    commit_file_change(
        octokit,
        owner=owner,
        repo=repo,
        branch=branch,
        change=change,
    )
    title = _truncate(f"[pr-guard:{kind}] {drift.quote}", 72)
    body = _render_body(drift, rationale, source_pr_number=source_pr_number, kind=kind)
    pr_number = open_pull_request(
        octokit,
        owner=owner,
        repo=repo,
        head=branch,
        base=default_branch,
        title=title,
        body=body,
        draft=draft,
    )
    return branch, pr_number


def _truncate(s: str, limit: int) -> str:
    return s if len(s) <= limit else s[: limit - 1].rstrip() + "…"


def _render_body(
    drift: DriftItem,
    rationale: str,
    *,
    source_pr_number: int,
    kind: str,
) -> str:
    return (
        f"Auto-generated **{kind}** for drift detected in #{source_pr_number}.\n"
        f"\n"
        f"## Source\n"
        f"- file: `{drift.source_file}:{drift.line}`\n"
        f"- spec: `{drift.source.upper()}` · severity `{drift.severity}` · "
        f"match score `{drift.score:.2f}`\n"
        f"\n"
        f"## Requirement (verbatim)\n"
        f"> {drift.quote}\n"
        f"\n"
        f"## Rationale (from pr-guard)\n"
        f"{rationale}\n"
        f"\n"
        f"---\n"
        f"_This PR was auto-generated by pr-guard-bot. Review carefully "
        f"before merging — bot-generated patches are starting points, not "
        f"finished work._"
    )
